name: fortnite_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.1
  percent_indicator: ^4.2.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
          style: italic
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
          weight: 900
          style: italic
